"""Base classes for code generators."""

from abc import ABC, abstractmethod
from typing import Dict, Any, List
from pathlib import Path
import jinja2
from graphflow_core.models import GraphDefinition, Step


class CodeGenerator(ABC):
    """
    Abstract base class for code generators.

    Subclasses implement framework-specific code generation.
    """

    def __init__(self):
        """Initialize code generator with template environment."""
        template_dir = Path(__file__).parent / "templates"
        self.jinja_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(template_dir)),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
        )

        # Add custom filters
        self.jinja_env.filters['repr'] = repr
        self.jinja_env.filters['json'] = self._json_filter

    def _json_filter(self, value: Any) -> str:
        """JSON filter for templates."""
        import json
        return json.dumps(value, indent=2)

    @abstractmethod
    def get_framework_name(self) -> str:
        """Return framework identifier (e.g., 'pydantic_ai', 'langgraph')."""
        pass

    def generate(self, graph: GraphDefinition, standalone: bool = True) -> str:
        """
        Generate Python code from graph definition.

        Args:
            graph: Graph definition to compile
            standalone: If True, include CLI/FastAPI wrappers

        Returns:
            Generated Python code
        """
        # Validate graph
        errors = graph.validate_graph_structure()
        if errors:
            raise ValueError(f"Invalid graph: {', '.join(errors)}")

        # Generate code sections
        imports = self.generate_imports(graph)
        memory_schema = self.generate_memory_schema(graph)
        agent_class = self.generate_agent_class(graph)
        standalone_code = self.generate_standalone_wrapper(graph) if standalone else ""

        # Combine sections
        code_parts = [
            self._generate_header(graph),
            imports,
            "",
            memory_schema,
            "",
            agent_class,
        ]

        if standalone:
            code_parts.extend(["", standalone_code])

        return "\n".join(code_parts)

    def _generate_header(self, graph: GraphDefinition) -> str:
        """Generate file header with metadata."""
        return f'''"""
Auto-generated by GraphFlow Compiler
Framework: {self.get_framework_name()}
Graph: {graph.metadata.name}
Generated: {graph.metadata.created}

{graph.metadata.description or ""}
"""'''

    def generate_imports(self, graph: GraphDefinition) -> str:
        """
        Generate import statements.

        Args:
            graph: Graph definition

        Returns:
            Import statements as string
        """
        base_imports = [
            "import asyncio",
            "from typing import Any, Dict",
            "from graphflow_core.memory import MemoryStore",
            "from graphflow_core.models import MemorySchema, FieldDefinition, SecretDefinition",
        ]

        framework_imports = self._get_framework_imports(graph)
        step_imports = self._get_step_imports(graph)

        all_imports = base_imports + framework_imports + step_imports
        return "\n".join(all_imports)

    @abstractmethod
    def _get_framework_imports(self, graph: GraphDefinition) -> List[str]:
        """Get framework-specific imports."""
        pass

    def _get_step_imports(self, graph: GraphDefinition) -> List[str]:
        """Get imports for step types used in graph."""
        step_types = {step.type for step in graph.steps}
        imports = []

        # Check if we need specific step implementations
        if "llm" in step_types:
            imports.append("# LLM step will use framework-specific implementation")

        return imports

    def generate_memory_schema(self, graph: GraphDefinition) -> str:
        """
        Generate memory schema definition.

        Args:
            graph: Graph definition

        Returns:
            Python code defining MEMORY_SCHEMA
        """
        template = self.jinja_env.get_template("memory_schema.py.jinja")
        return template.render(memory=graph.memory)

    @abstractmethod
    def generate_agent_class(self, graph: GraphDefinition) -> str:
        """
        Generate main agent class.

        This is framework-specific and must be implemented by subclasses.

        Args:
            graph: Graph definition

        Returns:
            Python code for agent class
        """
        pass

    def generate_standalone_wrapper(self, graph: GraphDefinition) -> str:
        """
        Generate standalone execution wrapper (CLI + optional FastAPI).

        Args:
            graph: Graph definition

        Returns:
            Python code for standalone execution
        """
        template = self.jinja_env.get_template("standalone.py.jinja")
        return template.render(
            graph=graph,
            input_keys=list(graph.memory.inputs.keys()),
            output_keys=list(graph.memory.outputs.keys()),
        )

    def get_step_execution_code(self, step: Step, graph: GraphDefinition) -> str:
        """
        Generate execution code for a specific step.

        Args:
            step: Step definition
            graph: Graph definition

        Returns:
            Python code to execute the step
        """
        if step.type == "start":
            return "# Start step - no operation"

        elif step.type == "output":
            return self._generate_output_step_code(step)

        elif step.type == "transform":
            return self._generate_transform_step_code(step)

        elif step.type == "conditional":
            return self._generate_conditional_step_code(step)

        elif step.type == "llm":
            return self._generate_llm_step_code(step, graph)

        elif step.type == "http":
            return self._generate_http_step_code(step)

        elif step.type == "join":
            return "# Join step - synchronization handled by execution flow"

        else:
            # Generic step execution
            return f"""
# Execute {step.type} step
step_class = StepRegistry.get("{step.type}")
step = step_class(
    id="{step.id}",
    config={repr(step.config)},
    memory_reads={repr(step.memory_reads)},
    memory_writes={repr(step.memory_writes)}
)
await step.execute(self.memory)
"""

    def _generate_output_step_code(self, step: Step) -> str:
        """Generate code for output step."""
        mapping = step.config.get("mapping", {})
        lines = ["# Output step - map to outputs"]
        for output_key, source_key in mapping.items():
            lines.append(f'self.memory.write("{output_key}", self.memory.read("{source_key}"))')
        return "\n".join(lines)

    def _generate_transform_step_code(self, step: Step) -> str:
        """Generate code for transform step."""
        code = step.config.get("code", "")
        output_key = step.config.get("output_key")
        input_keys = step.config.get("input_keys", step.memory_reads)

        # Build context
        context_lines = ["# Transform step"]
        for key in input_keys:
            var_name = key.replace('.', '_')
            context_lines.append(f'{var_name} = self.memory.read("{key}")')

        # Execute transform
        context_lines.append("def _transform():")
        for line in code.split('\n'):
            context_lines.append(f"    {line}")

        context_lines.append(f'_result = _transform()')
        context_lines.append(f'self.memory.write("{output_key}", _result)')

        return "\n".join(context_lines)

    def _generate_conditional_step_code(self, step: Step) -> str:
        """Generate code for conditional step."""
        condition = step.config.get("condition")
        result_key = step.config.get("result_key")

        lines = ["# Conditional step"]
        for key in step.memory_reads:
            var_name = key.replace('.', '_')
            lines.append(f'{var_name} = self.memory.read("{key}")')

        # Adjust condition for dotted keys
        adjusted_condition = condition
        for key in step.memory_reads:
            if '.' in key:
                adjusted_condition = adjusted_condition.replace(key, key.replace('.', '_'))

        lines.append(f'_condition_result = {adjusted_condition}')
        lines.append(f'self.memory.write("{result_key}", bool(_condition_result))')

        return "\n".join(lines)

    @abstractmethod
    def _generate_llm_step_code(self, step: Step, graph: GraphDefinition) -> str:
        """Generate framework-specific LLM step code."""
        pass

    def _generate_http_step_code(self, step: Step) -> str:
        """Generate code for HTTP step."""
        return """
# HTTP step
import httpx
async with httpx.AsyncClient() as client:
    response = await client.request(
        method="{method}",
        url="{url}",
        headers={headers},
        json={body}
    )
    self.memory.write("{response_key}", response.json())
""".format(
            method=step.config.get("method", "GET"),
            url=step.config.get("url", ""),
            headers=repr(step.config.get("headers", {})),
            body=repr(step.config.get("body", {})),
            response_key=step.config.get("response_key")
        )
