"""Base classes for code generators."""

import re
from abc import ABC, abstractmethod
from typing import Dict, Any, List, Set
from pathlib import Path
import jinja2
from graphflow_core.models import GraphDefinition, Step, ToolDefinition, MappedStepTool, MCPTool
from graphflow_core.steps.registry import StepRegistry
from graphflow_core.memory.resolver import TemplateResolver
from graphflow_compiler.tools.compiler import ToolCompiler


class CodeGenerator(ABC):
    """
    Abstract base class for code generators.

    Subclasses implement framework-specific code generation.
    """

    def __init__(self):
        """Initialize code generator with template environment."""
        template_dir = Path(__file__).parent / "templates"
        self.jinja_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(template_dir)),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
        )

        # Add custom filters
        self.jinja_env.filters['repr'] = repr
        self.jinja_env.filters['json'] = self._json_filter
        self.jinja_env.filters['pythonize'] = self._pythonize_filter

    def _json_filter(self, value: Any) -> str:
        """JSON filter for templates."""
        import json
        return json.dumps(value, indent=2)

    def _pythonize_filter(self, value: str) -> str:
        """Sanitize a string to be a valid Python identifier."""
        # Replace dots and other invalid characters with underscores
        return value.replace('.', '_').replace('-', '_').replace(' ', '_')

    def _resolve_memory_reference(self, value: Any, graph: GraphDefinition) -> Any:
        """
        Resolve a memory reference to its default value from the memory schema.

        If value is a string like "{memory.llm_2.tools}", looks up the default value
        from the memory schema. Otherwise returns the value as-is.

        Uses TemplateResolver for pattern matching.

        Args:
            value: Config value that might be a memory reference
            graph: Graph definition containing memory schema

        Returns:
            Resolved value (default from memory schema) or original value
        """
        if not isinstance(value, str):
            return value

        # Check if this is a memory reference using TemplateResolver
        refs = TemplateResolver.find_references(value)
        if not refs:
            return value

        # Get the first reference (typically only one for config values)
        full_key = next(iter(refs))

        # Only resolve memory namespace references to schema defaults
        if not full_key.startswith("memory."):
            return value

        memory_key = full_key[7:]  # Remove "memory." prefix

        # Look up in memory schema (intermediate, inputs, or outputs)
        for namespace in [graph.memory.intermediate, graph.memory.inputs, graph.memory.outputs]:
            if memory_key in namespace:
                field_def = namespace[memory_key]
                if hasattr(field_def, 'default') and field_def.default is not None:
                    return field_def.default
                break

        # If no default found, return original value
        return value

    @abstractmethod
    def get_framework_name(self) -> str:
        """Return framework identifier (e.g., 'pydantic_ai', 'langgraph')."""
        pass

    def generate(self, graph: GraphDefinition, standalone: bool = True) -> str:
        """
        Generate Python code from graph definition.

        Args:
            graph: Graph definition to compile
            standalone: If True, include CLI/FastAPI wrappers

        Returns:
            Generated Python code
        """
        # Validate graph
        errors = graph.validate_graph_structure()
        if errors:
            raise ValueError(f"Invalid graph: {', '.join(errors)}")

        # Generate code sections
        imports = self.generate_imports(graph)
        memory_schema = self.generate_memory_schema(graph)
        agent_class = self.generate_agent_class(graph)
        standalone_code = self.generate_standalone_wrapper(graph) if standalone else ""

        # Combine sections
        code_parts = [
            self._generate_header(graph),
            imports,
            "",
            memory_schema,
            "",
            agent_class,
        ]

        if standalone:
            code_parts.extend(["", standalone_code])

        return "\n".join(code_parts)

    def _generate_header(self, graph: GraphDefinition) -> str:
        """Generate file header with metadata."""
        return f'''"""
Auto-generated by GraphFlow Compiler
Framework: {self.get_framework_name()}
Graph: {graph.metadata.name}
Generated: {graph.metadata.created}

{graph.metadata.description or ""}
"""'''

    def generate_imports(self, graph: GraphDefinition) -> str:
        """
        Generate import statements.

        Args:
            graph: Graph definition

        Returns:
            Import statements as string
        """
        base_imports = [
            "import asyncio",
            "from typing import Any, Dict",
            "from graphflow_core.memory import MemoryStore",
            "from graphflow_core.models import MemorySchema, FieldDefinition, SecretDefinition",
        ]

        framework_imports = self._get_framework_imports(graph)
        step_imports = self._get_step_imports(graph)

        all_imports = base_imports + framework_imports + step_imports
        return "\n".join(all_imports)

    @abstractmethod
    def _get_framework_imports(self, graph: GraphDefinition) -> List[str]:
        """Get framework-specific imports."""
        pass

    def _get_step_imports(self, graph: GraphDefinition) -> List[str]:
        """Get imports for step types used in graph."""
        step_types = {step.type for step in graph.steps}
        imports = []

        # Check if we need specific step implementations
        if "llm" in step_types:
            imports.append("# LLM step will use framework-specific implementation")

        # Check for plugin imports based on step type patterns
        plugins_needed = set()
        for step_type in step_types:
            if step_type.startswith("http."):
                plugins_needed.add("graphflow_http")
            # Add more plugin patterns here as needed
            # elif step_type.startswith("database."):
            #     plugins_needed.add("graphflow_database")

        # Add plugin imports (must come before StepRegistry to trigger registration)
        for plugin in sorted(plugins_needed):
            imports.append(f"import {plugin}")

        # Import StepRegistry if we have any steps (all steps use it for execution)
        if step_types:
            imports.append("from graphflow_core.steps.registry import StepRegistry")

        return imports

    def generate_memory_schema(self, graph: GraphDefinition) -> str:
        """
        Generate memory schema definition.

        Args:
            graph: Graph definition

        Returns:
            Python code defining MEMORY_SCHEMA
        """
        template = self.jinja_env.get_template("memory_schema.py.jinja")
        return template.render(memory=graph.memory)

    @abstractmethod
    def generate_agent_class(self, graph: GraphDefinition) -> str:
        """
        Generate main agent class.

        This is framework-specific and must be implemented by subclasses.

        Args:
            graph: Graph definition

        Returns:
            Python code for agent class
        """
        pass

    def generate_standalone_wrapper(self, graph: GraphDefinition) -> str:
        """
        Generate standalone execution wrapper (CLI + optional FastAPI).

        Args:
            graph: Graph definition

        Returns:
            Python code for standalone execution
        """
        template = self.jinja_env.get_template("standalone.py.jinja")
        return template.render(
            graph=graph,
            input_keys=list(graph.memory.inputs.keys()),
            output_keys=list(graph.memory.outputs.keys()),
        )

    def get_step_execution_code(self, step: Step, graph: GraphDefinition) -> str:
        """
        Generate execution code for a specific step using step-level templates.

        This method implements the template-based code generation system:
        1. Get step class from registry
        2. Ask step for framework-specific template
        3. If template provided, render it with context
        4. If no template, use generic default execution

        Args:
            step: Step definition
            graph: Graph definition

        Returns:
            Python code to execute the step
        """
        # Get step class from registry
        try:
            step_class = StepRegistry.get(step.type)
        except (KeyError, ValueError):
            # Unknown step type - use generic execution
            return self._generate_generic_step_code(step)

        # Check if step provides a framework-specific template
        template_str = step_class.get_code_template(self.get_framework_name())

        if template_str:
            # Step provides custom template - use it
            return self._render_step_template(template_str, step, graph)
        else:
            # No custom template - use generic execution or legacy method
            return self._generate_generic_step_code(step)

    def _render_step_template(self, template_str: str, step: Step, graph: GraphDefinition) -> str:
        """
        Render a step template with context.

        Args:
            template_str: Jinja2 template string
            step: Step definition
            graph: Graph definition

        Returns:
            Rendered code
        """
        # Prepare template context
        context = self._prepare_step_template_context(step, graph)

        # Render template
        template = self.jinja_env.from_string(template_str)
        return template.render(**context)

    def _prepare_step_template_context(self, step: Step, graph: GraphDefinition) -> Dict[str, Any]:
        """
        Prepare context variables for step template rendering.

        Args:
            step: Step definition
            graph: Graph definition

        Returns:
            Dict of context variables
        """
        # Extract memory references from config and prompts
        memory_refs = self._extract_memory_refs(step.config)

        # Helper function to convert JSON types to Python types
        def json_type_to_python(json_type: str) -> str:
            type_map = {
                "string": "str",
                "number": "float",
                "integer": "int",
                "boolean": "bool",
                "array": "list",
                "object": "dict",
                "any": "Any",
            }
            return type_map.get(json_type, "Any")

        # Helper function for regex search
        def regex_search(text: str, pattern: str):
            """Helper for regex in templates."""
            import re
            match = re.search(pattern, text)
            return match

        # Parse and compile tools if present
        # Resolve memory reference if tools config is a memory binding like "{memory.step_id.tools}"
        tools_config_raw = step.config.get("tools", [])
        tools_config = self._resolve_memory_reference(tools_config_raw, graph)
        if not isinstance(tools_config, list):
            tools_config = []  # Fallback if resolution fails
        tool_definitions = self._parse_tools(tools_config)
        mcp_tools = self._parse_mcp_tools(tools_config)

        tool_code = ""
        tool_names = []
        tool_imports = []
        mcp_server_configs = {}

        compiler = ToolCompiler(self.get_framework_name())

        # Compile regular step-based tools
        if tool_definitions:
            # Use framework-specific tool compilation
            if self.get_framework_name() == "langgraph":
                # LangGraph uses factory pattern for closure-based memory access
                tool_code = compiler.compile_langgraph_tool_factory(tool_definitions)
            else:
                # Pydantic AI uses standalone functions
                tool_code = compiler.compile_tools(tool_definitions)
            tool_names = compiler.get_tool_names(tool_definitions)
            tool_imports = compiler.get_tool_imports(tool_definitions)

        # Compile MCP tools
        mcp_tool_names = []
        if mcp_tools:
            # Build server configs dict for template
            for mcp_tool in mcp_tools:
                server_key = mcp_tool.server.get_server_key()
                if server_key not in mcp_server_configs:
                    mcp_server_configs[server_key] = {
                        "transport": mcp_tool.server.transport,
                        "command": mcp_tool.server.command,
                        "args": mcp_tool.server.args,
                        "env": mcp_tool.server.env,
                        "url": mcp_tool.server.url,
                        "headers": mcp_tool.server.headers,
                        "timeout": mcp_tool.server.timeout,
                    }

            # Generate MCP tool code
            if self.get_framework_name() == "langgraph":
                # LangGraph: generate factory with both step and MCP tools
                mcp_tool_code = compiler.compile_langgraph_mcp_tool_factory(tool_definitions, mcp_tools)
                if mcp_tool_code:
                    tool_code = mcp_tool_code  # Replaces regular factory with combined
            else:
                # Pydantic AI: compile MCP tools and combine with regular tools
                mcp_tool_code = compiler.compile_mcp_tools(mcp_tools)
                if tool_code and mcp_tool_code:
                    tool_code = tool_code + "\n\n" + mcp_tool_code
                elif mcp_tool_code:
                    tool_code = mcp_tool_code

            mcp_tool_names = compiler.get_mcp_tool_names(mcp_tools)
            tool_names.extend(mcp_tool_names)
            # Add MCP tool imports (includes RunContext for pydantic_ai)
            mcp_imports = compiler.get_mcp_tool_imports(mcp_tools)
            tool_imports.extend(mcp_imports)

        return {
            "step": step,
            "graph": graph,
            "config": step.config,
            "outputs": step.outputs,
            "memory_reads": step.memory_reads,
            "memory_writes": step.memory_writes,
            "memory_refs": memory_refs,
            "framework": self.get_framework_name(),
            "json_type_to_python": json_type_to_python,
            "regex_search": regex_search,
            # Extract specific config values for convenience (resolve memory references to defaults)
            "provider": self._resolve_memory_reference(step.config.get("provider"), graph) or "ollama",
            "model": self._resolve_memory_reference(step.config.get("model"), graph),
            "system_prompt": self._resolve_memory_reference(step.config.get("system_prompt"), graph) or "",
            "user_prompt": self._resolve_memory_reference(step.config.get("user_prompt"), graph) or "",
            "output_schema": self._resolve_memory_reference(step.config.get("output_schema"), graph),
            "output_key": self._resolve_memory_reference(step.config.get("output_key"), graph),
            "temperature": self._resolve_memory_reference(step.config.get("temperature"), graph) or 0.7,
            "max_tokens": self._resolve_memory_reference(step.config.get("max_tokens"), graph),
            "api_key_secret": self._resolve_memory_reference(step.config.get("api_key_secret"), graph),
            "base_url": self._resolve_memory_reference(step.config.get("base_url"), graph),
            # History configuration for multi-turn conversations (enabled by default)
            "history_enabled": step.config.get("history_enabled", True),
            # Tool-related context
            "tools": tool_definitions,
            "tool_code": tool_code,
            "tool_names": tool_names,
            "tool_imports": tool_imports,
            # MCP tool context
            "mcp_tools": mcp_tools,
            "mcp_server_configs": mcp_server_configs,
            "mcp_tool_names": mcp_tool_names,
        }

    def _parse_tools(self, tools_config: List[Any]) -> List[ToolDefinition]:
        """
        Parse tools from config into ToolDefinition objects.

        Handles both MappedStepTool format (from frontend) and raw dicts.

        Args:
            tools_config: List of tool configs from step config

        Returns:
            List of ToolDefinition objects
        """
        tool_definitions = []

        for tool_entry in tools_config:
            if isinstance(tool_entry, dict):
                # Check if it's a MappedStepTool (from frontend)
                if tool_entry.get("type") == "mapped_step":
                    definition_dict = tool_entry.get("definition", {})
                    try:
                        tool_def = ToolDefinition(**definition_dict)
                        tool_definitions.append(tool_def)
                    except Exception as e:
                        # Log error but continue with other tools
                        print(f"Warning: Failed to parse tool definition: {e}")
                # Could also handle FunctionTool type here in future
            elif isinstance(tool_entry, ToolDefinition):
                tool_definitions.append(tool_entry)

        return tool_definitions

    def _parse_mcp_tools(self, tools_config: List[Any]) -> List[MCPTool]:
        """
        Parse MCP tools from config into MCPTool objects.

        Args:
            tools_config: List of tool configs from step config

        Returns:
            List of MCPTool objects
        """
        from graphflow_core.models import MCPServerConfig, MCPToolDefinition

        mcp_tools = []

        for tool_entry in tools_config:
            if isinstance(tool_entry, dict):
                # Check if it's an MCP tool
                if tool_entry.get("type") == "mcp":
                    try:
                        # Parse server config
                        server_dict = tool_entry.get("server", {})
                        server = MCPServerConfig(**server_dict)

                        # Parse tool definition
                        definition_dict = tool_entry.get("definition", {})
                        definition = MCPToolDefinition(**definition_dict)

                        mcp_tool = MCPTool(server=server, definition=definition)
                        mcp_tools.append(mcp_tool)
                    except Exception as e:
                        print(f"Warning: Failed to parse MCP tool: {e}")
            elif isinstance(tool_entry, MCPTool):
                mcp_tools.append(tool_entry)

        return mcp_tools

    def _extract_memory_refs(self, config: Dict[str, Any]) -> Set[str]:
        """
        Extract memory variable names from config (without namespace prefix).

        Uses centralized TemplateResolver for pattern matching, but strips
        the "memory." prefix for backwards compatibility with code templates.

        Args:
            config: Step configuration dict

        Returns:
            Set of memory variable names (e.g., "user_input", "query")
            Note: Only returns variables from memory namespace, not config/env/secrets
        """
        full_refs = TemplateResolver.find_references_in_dict(config)
        # Extract only memory namespace refs and strip the "memory." prefix
        return {ref[7:] for ref in full_refs if ref.startswith("memory.")}

    def _generate_generic_step_code(self, step: Step) -> str:
        """
        Generate generic step execution code.

        This is the default fallback for steps that don't provide
        custom templates. It instantiates the step class and calls execute().

        Args:
            step: Step definition

        Returns:
            Generic execution code
        """
        return f"""# Execute {step.type} step
step_class = StepRegistry.get("{step.type}")
step = step_class(
    id="{step.id}",
    config={repr(step.config)},
    outputs={repr(step.outputs)}
)
await step.execute(self.memory)
"""

    def _generate_output_step_code(self, step: Step) -> str:
        """Generate code for output step."""
        lines = ["# Output step - map to outputs"]

        for output_name, source_template in step.outputs.items():
            refs = TemplateResolver.find_references(source_template)
            if refs:
                source_key = next(iter(refs))
                lines.append(f'self.memory.write("memory.{output_name}", self.memory.read("{source_key}"))')

        return "\n".join(lines)

    def _generate_transform_step_code(self, step: Step) -> str:
        """Generate code for transform step."""
        code = step.config.get("code", "")
        output_key = step.config.get("output_key")
        input_keys = step.config.get("input_keys", step.memory_reads)

        # Build context
        context_lines = ["# Transform step"]
        for key in input_keys:
            var_name = key.replace('.', '_')
            context_lines.append(f'{var_name} = self.memory.read("memory.{key}")')

        # Execute transform
        context_lines.append("def _transform():")
        for line in code.split('\n'):
            context_lines.append(f"    {line}")

        context_lines.append(f'_result = _transform()')
        context_lines.append(f'self.memory.write("memory.{output_key}", _result)')

        return "\n".join(context_lines)

    def _generate_conditional_step_code(self, step: Step) -> str:
        """Generate code for conditional step."""
        condition = step.config.get("condition")
        result_key = step.config.get("result_key")

        lines = ["# Conditional step"]
        for key in step.memory_reads:
            var_name = key.replace('.', '_')
            lines.append(f'{var_name} = self.memory.read("memory.{key}")')

        # Adjust condition for dotted keys
        adjusted_condition = condition
        for key in step.memory_reads:
            if '.' in key:
                adjusted_condition = adjusted_condition.replace(key, key.replace('.', '_'))

        lines.append(f'_condition_result = {adjusted_condition}')
        lines.append(f'self.memory.write("memory.{result_key}", bool(_condition_result))')

        return "\n".join(lines)

    @abstractmethod
    def _generate_llm_step_code(self, step: Step, graph: GraphDefinition) -> str:
        """Generate framework-specific LLM step code."""
        pass

    def _generate_http_step_code(self, step: Step) -> str:
        """Generate code for HTTP step."""
        lines = ["# HTTP GET step", "import httpx", ""]

        # Read config values from memory
        for key, value in step.config.items():
            if isinstance(value, str) and TemplateResolver.contains_bindings(value):
                refs = TemplateResolver.find_references(value)
                if refs:
                    mem_key = next(iter(refs))
                    var_name = key
                    lines.append(f'{var_name} = self.memory.read("{mem_key}")')

        lines.append("")
        lines.append("# Make HTTP request")
        lines.append("async with httpx.AsyncClient() as client:")
        lines.append("    response = await client.get(")
        lines.append("        url=url,")
        lines.append("        params=params if params else None,")
        lines.append("        headers=headers if headers else None,")
        lines.append("        timeout=timeout if timeout else 30.0,")
        lines.append("    )")
        lines.append("")

        # Write outputs to memory
        lines.append("# Write outputs to memory")
        for output_name, output_template in step.outputs.items():
            refs = TemplateResolver.find_references(output_template)
            if refs:
                output_key = next(iter(refs))
                if output_name == "response":
                    lines.append(f'self.memory.write("{output_key}", response.text)')
                elif output_name == "status_code":
                    lines.append(f'self.memory.write("{output_key}", response.status_code)')
                elif output_name == "headers":
                    lines.append(f'self.memory.write("{output_key}", dict(response.headers))')

        return "\n".join(lines)
